config/routes.rb
Refinery::Application.routes.draw do
 # resources :translations

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :translations do
      collection do
        post :update_positions
      end
    end
  end
end

# ActionController::Routing::Routes.draw do |map|
  # resources :trasnslations
  # map.namespace(:admin, :path_prefix => 'refinery') do |admin|
    # admin.resources :translations
  # end
# end

app/models/translation.rb
class Translation < ActiveRecord::Base

  acts_as_indexed :fields => [:name]

  validates_presence_of :name

  before_update { |record| Translation.cache_expire(record.name, record.locale, record.untranslated_was) }
  after_save    { |record| Translation.cache_write(record.name, record.locale, record.untranslated, record.value) }

  # will_paginate per_page
  def self.per_page
    20
  end

  # Caching methods
  def self.cache_key(name, locale, untranslated)
    "#{Refinery.base_cache_key}_translation_#{name}_#{locale.to_s}_#{Digest::MD5.hexdigest(untranslated)}"
  end

  def self.cache_read(name, locale, untranslated)
    Rails.cache.read(cache_key(name, locale, untranslated))
  end

  def self.cache_expire(name, locale, untranslated)
    Rails.cache.read(cache_key(name, locale, untranslated), nil)
  end

  def self.cache_write(name, locale, untranslated, value)
    Rails.cache.write(cache_key(name, locale, untranslated), value)
  end

  def self.for_block(name, wym = true)
    self.lookup(name, yield, wym)
  end

  def self.for_string(name, untranslated, wym = false)
    self.lookup(name, untranslated, wym)
  end

  def self.lookup(name, untranslated = nil, wym = false)
    locale = I18n.locale
    return untranslated if locale == Refinery::I18n.default_locale
    
    if translation = self.cache_read(name,locale,untranslated)
      return translation
    end if RefinerySetting.find_or_set(:i18n_frontend_cache_translation, true, {:scoping => 'refinery'})
    
    if ( translation = self.find(:first, :conditions => {:name => name.to_s, :locale => locale.to_s}) ).nil?
      (Refinery::I18n.locales.keys - [Refinery::I18n.default_frontend_locale]).each do |current_locale|
        if (translation = self.find(:first, :conditions => {:name => name, :locale => current_locale.to_s})).nil?
          Translation.create(:name => name, :locale => current_locale.to_s, 
                             :value => untranslated, :untranslated => untranslated,:wym => wym,
                             :fresh => false, :freshness_key => Digest::MD5.hexdigest(untranslated))
        end
      end
      translation = self.find(:first, :conditions => {:name => name.to_s, :locale => locale.to_s})
    else
      if translation.fresh
        unless translation.freshness_key == Digest::MD5.hexdigest(untranslated)
          translation.freshness_key = Digest::MD5.hexdigest(untranslated)
          translation.untranslated = untranslated
          translation.fresh = false
          translation.save
        end
      end
    end

    self.cache_write(name, locale, untranslated, translation.value) if RefinerySetting.find_or_set(:i18n_frontend_cache_translation, true, {:scoping => 'refinery'})
    translation.value
  end

end

app/controllers/admin/translations_controller.rb
class Admin::TranslationsController < Admin::BaseController

  crudify :translation, :title_attribute => :name, :order => "fresh, updated_at DESC, name ASC"
  
private  
  def paginate_all_translations
    if params[:language]
      @translations = Translation.paginate :page => params[:page],
                                                    :order => "fresh, updated_at DESC, name ASC",
                                                    :conditions => {:locale => params[:language]}
    else
      @translations = Translation.paginate :page => params[:page],
                                                    :order => "fresh, updated_at DESC, name ASC"    
    end
  end
end

app/views/admin/translations/_form.html.erb
<% form_for [:admin, @translation] do |f| -%>
  <h2>
    <%=t(".translating_key_from_default_to", 
          :key => @translation.name.titleize,
          :from => Refinery::I18n.locales[Refinery::I18n.default_locale], 
          :to => Refinery::I18n.locales[@translation.locale.to_sym]) %>
  </h2>
  <div class='field'>
    <%= f.label :untranslated, t('.untranslated') -%>
    <% if @translation.wym %>
      <%= sanitize @translation.untranslated, :tags => %w(p br), :attributes => [nil] %>
    <% else %>
      <p><%= sanitize @translation.untranslated, :tags => [nil], :attributes => [nil] %></p>
    <% end %>
  </div>
  
  <div class='field'>
    <%= f.label :value, t('.value') -%>
    <% if @translation.wym %>
      <%= f.text_area :value, :rows => 20, :class => "wymeditor widest" -%>
    <% else %>
      <%= f.text_field :value -%>
    <% end %>
  </div>
  
  <div class='field'>
    <%= f.label :fresh, t('.fresh') -%>
    <%= f.check_box :fresh -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions", :locals => {:f => f, :continue_editing => false} %>
<% end -%>

app/views/admin/translations/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'translations', :collection => @translations %>
</ul>
<%= render :partial => "/shared/admin/sortable_list", :locals => {:continue_reordering => (defined?(continue_reordering) ? continue_reordering : true)} %>

app/views/admin/translations/_translation.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(translation) -%>">
  <span class='title'>
    <%= image_tag("/images/refinery/icons/flags/#{translation.locale}.png") unless params[:language] %>
    <%=h translation.name.titleize %>
    <%= content_tag(:strong, t(".not_fresh")) unless translation.fresh %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_translation_path(translation),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_translation_path(translation),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :'data-confirm' => t('shared.admin.delete.message',
        :title => translation.name
      ),
        :'data-method' => :delete %>
  </span>
</li>

app/views/admin/translations/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/translations/index.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => admin_translations_url} %>
    </li>
  <% if !searching? and Translation.count > 1 %>
    <li>
      <%= link_to t('.reorder', :what => "Translations"), admin_translations_url, :id => "reorder_action", :class => "reorder_icon" %>
      <%= link_to t('refinery.reorder_done', :what => "Translations"), admin_translations_url, :id => "reorder_action_done", :style => "display: none;", :class => "reorder_icon" %>
    </li>
  <% end %>
  </ul>

    <% current_locale = params[:language] -%>
    <ul id='current_locale'>
      <li>
        <% if current_locale %>
          <%= link_to "#{Refinery::I18n::locales[current_locale]}
                      <span>#{t('.change_language')}</span>
                      <span style='display:none;'>#{t('shared.admin.form_actions.cancel')}</span>".html_safe,
                    "#",
                    :style => "background-image: url('/images/refinery/icons/flags/#{current_locale}.png');" %>
        <% else %>
          <%= link_to "#{t('.all_language')}<span>#{t('.change_language')}</span><span style='display:none;'> #{t('shared.admin.form_actions.cancel')}</span>".html_safe,
                      "#",
              :style => "background-image: url('/images/refinery/icons/flags/en.png');" %>
          
        <% end %>
      </li>
    </ul>
    <ul id='other_locales' style='display: none'>
      <% (Refinery::I18n.locales.keys - [Refinery::I18n.default_frontend_locale]).each do |locale| %>
        <li>
          <%= link_to Refinery::I18n.locales[locale],
                      params.dup.tap { |p| p[:language] = locale }, 
                      :style => "background-image: url('/images/refinery/icons/flags/#{locale}.png');" %>
        </li>
      <% end %>
    </ul>
  
</div>
<div id='records'>
  <% if params[:language] %>
    <h2><%= t('.language', :language => Refinery::I18n.locales[params[:language]]) %></h2>
  <% end %>
  <% if searching? %>
    <h2><%= t('admin.search_results_for', :query => params[:search]) %></h2>
    <% if @translations.any? %>
      <%= render :partial => "translation", :collection => @translations %>
    <% else %>
      <p><%= t('admin.search_no_results') %></p>
    <% end %>
  <% else %>
    <% if @translations.any? %>
      <%= will_paginate @translations, :previous_label => '&laquo;', :next_label => '&raquo;' %>
       <ul id='sortable_list'>
        <%= render :partial => 'translation', :collection => @translations %>
       </ul>
      <%= will_paginate @translations, :previous_label => '&laquo;', :next_label => '&raquo;' %>
    <% else %>
      <p>
        <strong>
          <%= t('.no_items_yet') %>
        </strong>
      </p>
    <% end %>
  <% end %>
</div>

app/views/admin/translations/new.html.erb
<%= render :partial => "form" %>

app/views/translations/index.html.erb
<% content_for :body_content_left do %>
  <ul id="translations">
    <% @translations.each do |translations| %>
      <li>
        <%= link_to translations.name, translations_url(translations) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>

app/views/translations/show.html.erb
<% content_for :body_content_title do %>
  <%= @translations.name %>
<% end %>

<% content_for :body_content_left do %>
  
  <div>
    <h3>Name</h3>
    <%=raw @translations.name %>
  </div>
  
  <div>
    <h3>Value</h3>
    <%=raw @translations.value %>
  </div>
  
<% end %>

<% content_for :body_content_right do %>
  <h2><%= t('.other') %></h2>
  <ul id="translations">
    <% @translations.each do |translations| %>
      <li>
        <%= link_to translations.name, translations_url(translations) %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= render :partial => "/shared/content_page" %>